### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by haimlichaa** [chirpstack/chirpstack-v3-to-v4#24]
go: downloading github.com/go-openapi/jsonreference v0.20.4                                                      
pkg/mod/github.com/charmbracelet/x/exp/ordered@v0.0.0-20231010190216-1cb11efc897d/ordered.go:3:8: package cmp is not in GOROOT (/usr/local/go/src/cmp)                                                                            
pkg/mod/github.com/goreleaser/goreleaser@v1.25.1/internal/builders/golang/build.go:11:2: package slices is not in GOROOT (/usr/local/go/src/slices)                                                                               
ERROR: Service 'chirpstack-v3-to-v4' failed to build : The command '/bin/sh -c go install github.com/goreleaser/goreleaser@latest' returned a non-zero code: 1

**Comment by brocaar** [comment]
Hi @haimlichaa, what command are you using for building the binary? Are you using:

https://github.com/chirpstack/chirpstack-v3-to-v4?tab=readme-ov-file#building-from-source

**Comment by haimlichaa** [comment]
Hi @brocaar ,
I used this : https://github.com/chirpstack/chirpstack-v3-to-v4.git

  I'm unable to just use make release because I'm behind a proxy and there seems to be a [bug ](https://forums.docker.com/t/proxy-issues-with-docker-build/99502)with docker which is preventing the proxy configuration from carrying over to the docker build (even with proxy configured in the docker service).    So instead I'm trying to just run docker-compose build directly and passed the proxy arguments directly.


```
docker-compose build --build-arg HTTP_PROXY=http://MYPROYY --build-arg HTTPS_PROXY=http://MYPROXY chirpstack-v3-to-v4

Building chirpstack-v3-to-v4
Step 1/7 : FROM golang:1.18-alpine
 ---> a77f45e5f987
Step 2/7 : ENV PROJECT_PATH=/chirpstack-v3-to-v4
 ---> Using cache
 ---> d527a3c971f0
Step 3/7 : RUN apk add --no-cache make git bash
 ---> Using cache
 ---> 9aa8c008ac79
Step 4/7 : RUN go install github.com/goreleaser/goreleaser@latest
 ---> Running in 8dab0e08c0fa
go: downloading github.com/goreleaser/goreleaser v1.25.1
go: downloading github.com/caarlos0/go-version v0.1.1                                                            
go: downloading github.com/caarlos0/log v0.4.4                                                                   
go: downloading github.com/charmbracelet/lipgloss v0.10.0                                                        
go: downloading github.com/muesli/termenv v0.15.2                                                                
go: downloading go.uber.org/automaxprocs v1.5.3                                                                  
go: downloading github.com/elliotchance/orderedmap/v2 v2.2.0                                                     
go: downloading github.com/caarlos0/ctrlc v1.2.0                                                                 
go: downloading github.com/invopop/jsonschema v0.12.0                                                            
go: downloading github.com/muesli/mango-cobra v1.2.0                                                             
go: downloading github.com/muesli/roff v0.1.0                                                                    
go: downloading github.com/spf13/cobra v1.8.0                                                                    
go: downloading github.com/aymanbagabas/go-osc52/v2 v2.0.1                                                       
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0                                                        
go: downloading github.com/mattn/go-isatty v0.0.20                                                               
go: downloading github.com/mattn/go-runewidth v0.0.15                                                            
go: downloading golang.org/x/sys v0.18.0                                                                         
go: downloading github.com/muesli/reflow v0.3.0                                                                  
go: downloading github.com/rivo/uniseg v0.4.7                                                                    
go: downloading github.com/hashicorp/go-multierror v1.1.1                                                        
go: downloading github.com/charmbracelet/x/exp/ordered v0.0.0-20231010190216-1cb11efc897d                        
go: downloading golang.org/x/exp v0.0.0-20231206192017-f3f8817b8deb                                              
go: downloading github.com/goreleaser/nfpm/v2 v2.36.1                                                            
go: downloading github.com/wk8/go-ordered-map/v2 v2.1.8                                                          
go: downloading github.com/muesli/mango v0.1.0                                                                   
go: downloading github.com/muesli/mango-pflag v0.1.0                                                             
go: downloading github.com/cpuguy83/go-md2man/v2 v2.0.3                                                          
go: downloading github.com/spf13/pflag v1.0.5                                                                    
go: downloading gopkg.in/yaml.v3 v3.0.1                                                                          
go: downloading code.gitea.io/sdk/gitea v0.17.1                                                                  
go: downloading github.com/google/go-github/v61 v61.0.0                                                          
go: downloading github.com/xanzy/go-gitlab v0.101.0                                                              
go: downloading golang.org/x/crypto v0.21.0                                                                      
go: downloading golang.org/x/oauth2 v0.18.0                                                                      
go: downloading github.com/Masterminds/semver/v3 v3.2.1                                                          
go: downloading golang.org/x/text v0.14.0                                                                        
go: downloading github.com/hashicorp/errwrap v1.1.0                                                              
go: downloading github.com/caarlos0/go-shellwords v1.0.12                                                        
go: downloading github.com/mitchellh/go-homedir v1.1.0                                                           
go: downloading dario.cat/mergo v1.0.0                                                                           
go: downloading github.com/docker/go-units v0.5.0                                                                
go: downloading github.com/bahlo/generic-list-go v0.2.0                                                          
go: downloading github.com/buger/jsonparser v1.1.1                                                               
go: downloading github.com/mailru/easyjson v0.7.7                                                                
go: downloading github.com/russross/blackfriday/v2 v2.1.0                                                        
go: downloading github.com/go-fed/httpsig v1.1.0                                                                 
go: downloading github.com/hashicorp/go-version v1.6.0                                                           
go: downloading github.com/google/go-querystring v1.1.0                                                          
go: downloading github.com/hashicorp/go-cleanhttp v0.5.2                                                         
go: downloading github.com/hashicorp/go-retryablehttp v0.7.5                                                     
go: downloading golang.org/x/time v0.5.0                                                                         
go: downloading github.com/caarlos0/env/v9 v9.0.0                                                                
go: downloading github.com/aws/aws-sdk-go v1.51.1                                                                
go: downloading gocloud.dev v0.37.0                                                                              
go: downloading github.com/awslabs/amazon-ecr-credential-helper/ecr-login v0.0.0-20231024185945-8841054dbdb8     
go: downloading github.com/chrismellard/docker-credential-acr-env v0.0.0-20230304212654-82a0ddb27589             
go: downloading github.com/google/go-containerregistry v0.19.1                                                   
go: downloading github.com/google/ko v0.15.2                                                                     
go: downloading golang.org/x/tools v0.19.0                                                                       
go: downloading github.com/mattn/go-mastodon v0.0.6                                                              
go: downloading github.com/caarlos0/go-reddit/v3 v3.0.1                                                          
go: downloading github.com/slack-go/slack v0.12.5                                                                
go: downloading gopkg.in/mail.v2 v2.3.1                                                                          
go: downloading github.com/atc0005/go-teams-notify/v2 v2.10.0                                                    
go: downloading github.com/go-telegram-bot-api/telegram-bot-api v4.6.4+incompatible                              
go: downloading github.com/dghubble/go-twitter v0.0.0-20211115160449-93a8679adecb                                
go: downloading github.com/dghubble/oauth1 v0.7.3                                                                
go: downloading github.com/goreleaser/fileglob v1.3.0                                                            
go: downloading golang.org/x/sync v0.6.0                                                                         
go: downloading github.com/AlekSi/pointer v1.2.0                                                                 
go: downloading github.com/goreleaser/chglog v0.5.0                                                              
go: downloading github.com/klauspost/pgzip v1.2.6                                                                
go: downloading github.com/klauspost/compress v1.17.7                                                            
go: downloading github.com/blakesmith/ar v0.0.0-20190502131153-809d4375e1fb                                      
go: downloading github.com/ulikunitz/xz v0.5.11                                                                  
go: downloading github.com/google/rpmpack v0.6.0                                                                 
go: downloading github.com/Azure/azure-sdk-for-go/sdk/azcore v1.10.0                                             
go: downloading github.com/Azure/azure-sdk-for-go v68.0.0+incompatible                                           
go: downloading github.com/Azure/azure-sdk-for-go/sdk/azidentity v1.5.1                                          
go: downloading github.com/Azure/azure-sdk-for-go/sdk/storage/azblob v1.3.1                                      
go: downloading github.com/Azure/go-autorest/autorest/to v0.4.0                                                  
go: downloading github.com/google/wire v0.6.0                                                                    
go: downloading github.com/Azure/go-autorest/autorest v0.11.29                                                   
go: downloading github.com/Azure/go-autorest v14.2.0+incompatible                                                
go: downloading cloud.google.com/go/compute/metadata v0.2.3                                                      
go: downloading cloud.google.com/go/iam v1.1.6                                                                   
go: downloading cloud.google.com/go/compute v1.25.0                                                              
go: downloading cloud.google.com/go v0.112.1                                                                     
go: downloading cloud.google.com/go/storage v1.39.1                                                              
go: downloading github.com/googleapis/gax-go/v2 v2.12.2                                                          
go: downloading google.golang.org/api v0.169.0                                                                   
go: downloading github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.16.9                                          
go: downloading github.com/aws/aws-sdk-go-v2/service/s3 v1.51.4                                                  
go: downloading github.com/aws/aws-sdk-go-v2 v1.25.3                                                             
go: downloading github.com/aws/smithy-go v1.20.1                                                                 
go: downloading go.opencensus.io v0.24.0                                                                         
go: downloading github.com/Azure/azure-sdk-for-go/sdk/keyvault/azkeys v0.10.0                                    
go: downloading cloud.google.com/go/kms v1.15.7                                                                  
go: downloading google.golang.org/grpc v1.62.1                                                                   
go: downloading github.com/aws/aws-sdk-go-v2/service/kms v1.29.2                                                 
go: downloading github.com/Azure/go-autorest/autorest/azure/auth v0.5.12                                         
go: downloading github.com/docker/docker-credential-helpers v0.8.0                                               
go: downloading github.com/sirupsen/logrus v1.9.3                                                                
go: downloading github.com/docker/cli v25.0.4+incompatible                                                       
go: downloading github.com/opencontainers/go-digest v1.0.0                                                       
go: downloading github.com/opencontainers/image-spec v1.1.0                                                      
go: downloading github.com/sigstore/cosign/v2 v2.2.3                                                             
go: downloading github.com/spf13/viper v1.18.2                                                                   
go: downloading github.com/gorilla/websocket v1.5.1                                                              
go: downloading github.com/tomnomnom/linkheader v0.0.0-20180905144013-02ca5825eb80                               
go: downloading golang.org/x/net v0.22.0                                                                         
go: downloading github.com/technoweenie/multipartstreamer v1.0.1                                                 
go: downloading github.com/cenkalti/backoff/v4 v4.2.1                                                            
go: downloading github.com/dghubble/sling v1.4.0                                                                 
go: downloading github.com/gobwas/glob v0.2.3                                                                    
go: downloading github.com/ProtonMail/go-crypto v1.0.0                                                           
go: downloading github.com/Masterminds/sprig/v3 v3.2.3                                                           
go: downloading github.com/go-git/go-git/v5 v5.11.0                                                              
go: downloading gitlab.com/digitalxero/go-conventional-commit v1.0.7                                             
go: downloading github.com/cavaliergopher/cpio v1.0.1                                                            
go: downloading github.com/jmespath/go-jmespath v0.4.0                                                           
go: downloading github.com/Azure/azure-sdk-for-go/sdk/internal v1.5.2                                            
go: downloading github.com/AzureAD/microsoft-authentication-library-for-go v1.2.2                                
go: downloading golang.org/x/xerrors v0.0.0-20231012003039-104605ab7028                                          
go: downloading google.golang.org/protobuf v1.33.0                                                               
go: downloading google.golang.org/genproto/googleapis/api v0.0.0-20240311173647-c811ad7063a7                     
go: downloading google.golang.org/genproto v0.0.0-20240311173647-c811ad7063a7                                    
go: downloading github.com/google/uuid v1.6.0                                                                    
go: downloading github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream v1.6.1                                     
go: downloading github.com/aws/aws-sdk-go-v2/internal/configsources v1.3.3                                       
go: downloading github.com/aws/aws-sdk-go-v2/internal/v4a v1.3.3                                                 
go: downloading github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding v1.11.1                            
go: downloading github.com/aws/aws-sdk-go-v2/service/internal/checksum v1.3.5                                    
go: downloading github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.11.5                              
go: downloading github.com/aws/aws-sdk-go-v2/service/internal/s3shared v1.17.3                                   
go: downloading github.com/aws/aws-sdk-go-v2/config v1.27.7                                                      
go: downloading github.com/Azure/azure-sdk-for-go/sdk/keyvault/internal v0.7.1                                   
go: downloading github.com/Azure/go-autorest/autorest/adal v0.9.23                                               
go: downloading github.com/Azure/go-autorest/autorest/azure/cli v0.4.6                                           
go: downloading github.com/Azure/go-autorest/logger v0.2.1                                                       
go: downloading github.com/dimchansky/utfbom v1.1.1                                                              
go: downloading github.com/aws/aws-sdk-go-v2/service/ecr v1.20.2                                                 
go: downloading github.com/aws/aws-sdk-go-v2/service/ecrpublic v1.18.2                                           
go: downloading google.golang.org/genproto/googleapis/rpc v0.0.0-20240311173647-c811ad7063a7                     
go: downloading github.com/pkg/errors v0.9.1                                                                     
go: downloading github.com/docker/docker v25.0.5+incompatible                                                    
go: downloading github.com/docker/distribution v2.8.3+incompatible                                               
go: downloading github.com/containerd/stargz-snapshotter/estargz v0.14.3                                         
go: downloading github.com/sigstore/sigstore v1.8.1                                                              
go: downloading sigs.k8s.io/kind v0.22.0                                                                         
go: downloading github.com/fsnotify/fsnotify v1.7.0                                                              
go: downloading github.com/mitchellh/mapstructure v1.5.0                                                         
go: downloading github.com/sagikazarmark/slog-shim v0.1.0                                                        
go: downloading github.com/spf13/afero v1.11.0                                                                   
go: downloading github.com/spf13/cast v1.6.0                                                                     
go: downloading golang.org/x/mod v0.16.0                                                                         
go: downloading github.com/Masterminds/goutils v1.1.1                                                            
go: downloading github.com/huandu/xstrings v1.3.3                                                                
go: downloading github.com/imdario/mergo v0.3.16                                                                 
go: downloading github.com/mitchellh/copystructure v1.2.0                                                        
go: downloading github.com/shopspring/decimal v1.2.0                                                             
go: downloading github.com/go-git/go-billy/v5 v5.5.0                                                             
go: downloading github.com/sergi/go-diff v1.2.0                                                                  
go: downloading github.com/emirpasic/gods v1.18.1                                                                
go: downloading github.com/kylelemons/godebug v1.1.0                                                             
go: downloading github.com/pkg/browser v0.0.0-20240102092130-5ac0b6a4141c                                        
go: downloading go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.49.0              
go: downloading go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.49.0                            
go: downloading go.opentelemetry.io/otel v1.24.0                                                                 
go: downloading go.opentelemetry.io/otel/trace v1.24.0                                                           
go: downloading github.com/google/s2a-go v0.1.7                                                                  
go: downloading github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.6.3                                        
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da                                  
go: downloading github.com/aws/aws-sdk-go-v2/credentials v1.17.7                                                 
go: downloading github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.15.3                                            
go: downloading github.com/aws/aws-sdk-go-v2/internal/ini v1.8.0                                                 
go: downloading github.com/aws/aws-sdk-go-v2/service/sso v1.20.2                                                 
go: downloading github.com/aws/aws-sdk-go-v2/service/ssooidc v1.23.2                                             
go: downloading github.com/aws/aws-sdk-go-v2/service/sts v1.28.4                                                 
go: downloading github.com/Azure/go-autorest/tracing v0.6.0                                                      
go: downloading github.com/Azure/go-autorest/autorest/date v0.3.0                                                
go: downloading github.com/golang-jwt/jwt/v4 v4.5.0                                                              
go: downloading github.com/vbatts/tar-split v0.11.5                                                              
go: downloading github.com/sigstore/rekor v1.3.4                                                                 
go: downloading github.com/letsencrypt/boulder v0.0.0-20231026200631-000cd05d5491                                
go: downloading github.com/secure-systems-lab/go-securesystemslib v0.8.0                                         
go: downloading golang.org/x/term v0.18.0                                                                        
go: downloading github.com/docker/go-connections v0.4.0                                                          
go: downloading github.com/distribution/reference v0.5.0                                                         
go: downloading github.com/subosito/gotenv v1.6.0                                                                
go: downloading github.com/hashicorp/hcl v1.0.1-vault-5                                                          
go: downloading gopkg.in/ini.v1 v1.67.0                                                                          
go: downloading github.com/magiconair/properties v1.8.7                                                          
go: downloading github.com/pelletier/go-toml/v2 v2.1.0                                                           
go: downloading github.com/cloudflare/circl v1.3.7                                                               
go: downloading github.com/pelletier/go-toml v1.9.5                                                              
go: downloading github.com/mitchellh/reflectwalk v1.0.2                                                          
go: downloading github.com/pjbgf/sha1cd v0.3.0                                                                   
go: downloading github.com/cyphar/filepath-securejoin v0.2.4                                                     
go: downloading github.com/go-git/gcfg v1.5.1-0.20230307220236-3a3c6141e376                                      
go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99                                  
go: downloading github.com/golang-jwt/jwt/v5 v5.2.1                                                              
go: downloading github.com/golang/protobuf v1.5.4                                                                
go: downloading go.opentelemetry.io/otel/metric v1.24.0                                                          
go: downloading github.com/googleapis/enterprise-certificate-proxy v0.3.2                                        
go: downloading github.com/felixge/httpsnoop v1.0.4                                                              
go: downloading github.com/go-logr/logr v1.4.1                                                                   
go: downloading github.com/go-openapi/errors v0.21.0                                                             
go: downloading github.com/go-openapi/runtime v0.27.1                                                            
go: downloading github.com/go-openapi/strfmt v0.22.0                                                             
go: downloading github.com/go-openapi/swag v0.22.9                                                               
go: downloading github.com/go-openapi/validate v0.22.4                                                           
go: downloading github.com/titanous/rocacheck v0.0.0-20171023193734-afe73141d399                                 
go: downloading github.com/alessio/shellescape v1.4.1                                                            
go: downloading gopkg.in/warnings.v0 v0.1.2                                                                      
go: downloading github.com/kevinburke/ssh_config v1.2.0                                                          
go: downloading github.com/skeema/knownhosts v1.2.1                                                              
go: downloading github.com/xanzy/ssh-agent v0.3.3                                                                
go: downloading github.com/go-logr/stdr v1.2.2                                                                   
go: downloading github.com/asaskevich/govalidator v0.0.0-20230301143203-a9d515a09cc2                             
go: downloading github.com/oklog/ulid v1.3.1                                                                     
go: downloading go.mongodb.org/mongo-driver v1.13.1                                                              
go: downloading github.com/gogo/protobuf v1.3.2                                                                  
go: downloading gopkg.in/go-jose/go-jose.v2 v2.6.3                                                               
go: downloading github.com/google/safetext v0.0.0-20220905092116-b49f7bc46da2                                    
go: downloading sigs.k8s.io/yaml v1.4.0                                                                          
go: downloading github.com/go-openapi/analysis v0.22.0                                                           
go: downloading github.com/go-openapi/jsonpointer v0.20.2                                                        
go: downloading github.com/go-openapi/loads v0.21.5                                                              
go: downloading github.com/go-openapi/spec v0.20.13                                                              
go: downloading github.com/josharian/intern v1.0.0                                                               
go: downloading github.com/BurntSushi/toml v1.2.1                                                                
go: downloading github.com/evanphx/json-patch/v5 v5.6.0                                                          
go: downloading github.com/go-openapi/jsonreference v0.20.4                                                      
pkg/mod/github.com/charmbracelet/x/exp/ordered@v0.0.0-20231010190216-1cb11efc897d/ordered.go:3:8: package cmp is not in GOROOT (/usr/local/go/src/cmp)                                                                            
pkg/mod/github.com/goreleaser/goreleaser@v1.25.1/internal/builders/golang/build.go:11:2: package slices is not in GOROOT (/usr/local/go/src/slices)                                                                               
ERROR: Service 'chirpstack-v3-to-v4' failed to build : The command '/bin/sh -c go install github.com/goreleaser/goreleaser@latest' returned a non-zero code: 1

```

**Comment by brocaar** [comment]
@haimlichaa could you do a `git pull` and retest? I though initially the issue was with the proxy, but in fact it was a dependency issue. The latest commit should fix the issue.

**Comment by haimlichaa** [comment]
Thank you!  I still can't run make release but running 
```
> docker-compose build --build-arg HTTP_PROXY=http://MYPROYY --build-arg HTTPS_PROXY=http://MYPROXY chirpstack-v3-to-v4 
Building chirpstack-v3-to-v4
Step 1/7 : FROM golang:1.22-alpine
 ---> 438d61874560
Step 2/7 : ENV PROJECT_PATH=/chirpstack-v3-to-v4
 ---> Using cache
 ---> 7173d171d8bd
Step 3/7 : RUN apk add --no-cache make git bash
 ---> Using cache
 ---> 9716434b8145
Step 4/7 : RUN go install github.com/goreleaser/goreleaser@v1.25.1
 ---> Using cache
 ---> 8abe6fc5aae7
Step 5/7 : RUN git config --global --add safe.directory $PROJECT_PATH
 ---> Using cache
 ---> 60af955d9c7a
Step 6/7 : RUN mkdir -p $PROJECT_PATH
 ---> Using cache
 ---> 4eb4cbc965e3
Step 7/7 : WORKDIR $PROJECT_PATH
 ---> Using cache
 ---> 549d7ab68161

Successfully built 549d7ab68161
Successfully tagged chirpstack-v3-to-v4old_chirpstack-v3-to-v4:latest



> docker-compose up
Starting chirpstack-v3-to-v4old_chirpstack-v3-to-v4_1 ... done
Attaching to chirpstack-v3-to-v4old_chirpstack-v3-to-v4_1
chirpstack-v3-to-v4old_chirpstack-v3-to-v4_1 exited with code 0
```
now succeeds, but I'm not seeing the built utility.

**Comment by brocaar** [comment]
This is the proper command to execute (with the proxy arguments added):

https://github.com/chirpstack/chirpstack-v3-to-v4/blob/129c86e4301226cee32074459e2821e572b32a93/Makefile#L14

**Comment by haimlichaa** [comment]
OK figured it out. docker-compose run doesn't accept proxy aruguments however Dockerfile does.  Just had to add ENV HTTPS_PROXY/HTTP_PROXY to the supplied Dockerfile-devel.
But now AFter the image gets built, I get this error:

```
> make release
...
...

Successfully built 85e682106d37
Successfully tagged chirpstack-v3-to-v4_chirpstack-v3-to-v4:latest
WARNING: Image for service chirpstack-v3-to-v4 was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating chirpstack-v3-to-v4_chirpstack-v3-to-v4_run ... done
  • starting release...
  • loading                                          path=.goreleaser.yaml
  • loading environment variables
  • getting and validating git state
    • git state                                      commit=129c86e4301226cee32074459e2821e572b32a93 branch=master current_tag=v4.0.9 previous_tag=v4.0.8 dirty=true
  ⨯ release failed after 0s                          error=git is in a dirty state
Please check in your pipeline what can be changing the following files:
 M Dockerfile-devel

Learn more at https://goreleaser.com/errors/dirty

make: *** [Makefile:11: release] Error 1
```

**Comment by brocaar** [comment]
Try the "make snapshot" instead. The "make release" only works if the
current commit is a tagged version. These commands provide equal binaries,
it is just about the versioning.

**Comment by haimlichaa** [comment]
That worked thank you
